//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonkeyPuzzleResultViewer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Mark
    {
        public int markID { get; set; }
        public int userID { get; set; }
        public int testID { get; set; }
        [DisplayName("Mark")]
        public int Mark1 { get; set; }
        public Nullable<int> Percentage { get; set; }
    
        public virtual Test Test { get; set; }
        public virtual User User { get; set; }
    }
}
