//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonkeyPuzzleResultViewer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Question
    {
        public int questionID { get; set; }
        [DisplayName("Question")]
        public string Question1 { get; set; }
        public int testID { get; set; }
        [DisplayName("A)")]
        public string AnswerA { get; set; }
        [DisplayName("B)")]
        public string AnswerB { get; set; }
        [DisplayName("C)")]
        public string AnswerC { get; set; }
        [DisplayName("D)")]
        public string AnswerD { get; set; }
        [DisplayName("Correct Answer")]
        public string CorrectAnswer { get; set; }

        [Required(ErrorMessage = "Please select an answer!")]
        public string SelectedAnswer { get; set; }
    
        public virtual Test Test { get; set; }
    }
}
